version: '3'

services: #los contenedores que vamos a usar
  web:
    container_name: appNode
    restart: always
    build: .
    ports:
      - 5000:3000
    volumes:
      - .:/app
  mongo:
    container_name: mongodatabase
    image: mongo:5.0
    ports:
      - 27017:27017
