version: '3'

services: #los contenedores que vamos a usar
  web:
    container_name: appNode
    restart: always
    build: .
    ports:
      - published: 5000
        target: 3000
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodatabase
    image: mongo
    logging:
      driver: none
    ports:
      - published: 27017
        target: 27017
